version: '3.8'

services:
  puppygraph:
    image: puppygraph/puppygraph:stable
    container_name: puppy
    pull_policy: always
    ports:
      - "8081:8081"
      - "8182:8182"
      - "7687:7687"
    environment:
      - PUPPYGRAPH_PASSWORD=puppygraph123
      - QUERY_TIMEOUT=5m
      - STORAGE_PATH_ROOT=/data/storage
    volumes:
      - puppygraph-data:/data/storage
    restart: unless-stopped

volumes:
  puppygraph-data: